const job_data=[
    {
        "job_id": 1,
        "job_desc": "euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula",
        "compnay_name": "Google",
        "date": "2018-02-01",
        "city": "Yakima",
        "state": "Washington",
        "country": "India",
        "job_type": "Full-time",
        "title": "Nurse"
    },
    {
        "job_id": 2,
        "job_desc": "diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et",
        "compnay_name": "Google",
        "date": "2018-02-10",
        "city": "Arlington",
        "state": "Virginia",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Business Systems Development Analyst"
    },
    {
        "job_id": 3,
        "job_desc": "amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla",
        "compnay_name": "Google",
        "date": "2018-02-12",
        "city": "Jackson",
        "state": "Mississippi",
        "country": "India",
        "job_type": "Full-time",
        "title": "Clinical Specialist"
    },
    {
        "job_id": 4,
        "job_desc": "quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque",
        "compnay_name": "Google",
        "date": "2018-01-01",
        "city": "Houston",
        "state": "Texas",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Internal Auditor"
    },
    {
        "job_id": 5,
        "job_desc": "quam a odio in hac habitasse platea dictumst maecenas ut",
        "compnay_name": "Google",
        "date": "2018-08-01",
        "city": "Metairie",
        "state": "Louisiana",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Assistant Media Planner"
    },
    {
        "job_id": 6,
        "job_desc": "porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor",
        "compnay_name": "Google",
        "date": "2018-07-01",
        "city": "Philadelphia",
        "state": "Pennsylvania",
        "country": "India",
        "job_type": "Full-time",
        "title": "Recruiter"
    },
    {
        "job_id": 7,
        "job_desc": "id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas",
        "compnay_name": "Thoughtstorm",
        "date": "2018-06-01",
        "city": "San Jose",
        "state": "California",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Chief Design Engineer"
    },
    {
        "job_id": 8,
        "job_desc": "imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum",
        "compnay_name": "Google",
        "date": "2018-03-01",
        "city": "Dallas",
        "state": "Texas",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Research Nurse"
    },
    {
        "job_id": 9,
        "job_desc": "suspendisse ornare consequat lectus in est risus auctor sed tristique",
        "compnay_name": "Google",
        "date": "2018-08-01",
        "city": "Peoria",
        "state": "Illinois",
        "country": "United Kingdom",
        "job_type": "Part-time",
        "title": "Project Manager"
    },
    {
        "job_id": 10,
        "job_desc": "odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac",
        "compnay_name": "Google",
        "date": "2018-02-21",
        "city": "Denver",
        "state": "Colorado",
        "country": "United Kingdom",
        "job_type": "Full-time",
        "title": "Marketing Assistant"
    },
    {
        "job_id": 11,
        "job_desc": "adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis",
        "compnay_name": "Google",
        "date": "2018-02-11",
        "city": "Clearwater",
        "state": "Florida",
        "country": "United Kingdom",
        "job_type": "Part-time",
        "title": "Clinical Specialist"
    },
    {
        "job_id": 12,
        "job_desc": "pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac",
        "compnay_name": "Facebook",
        "date": "2018-02-01",
        "city": "Pocatello",
        "state": "Idaho",
        "country": "United Kingdom",
        "job_type": "Full-time",
        "title": "Recruiting Manager"
    },
    {
        "job_id": 13,
        "job_desc": "phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id",
        "compnay_name": "Facebook",
        "date": "2018-02-14",
        "city": "Cleveland",
        "state": "Ohio",
        "country": "Germany",
        "job_type": "Part-time",
        "title": "Graphic Designer"
    },
    {
        "job_id": 14,
        "job_desc": "dui luctus rutrum nulla tellus in sagittis dui vel nisl duis",
        "compnay_name": "Facebook",
        "date": "2018-04-01",
        "city": "Orlando",
        "state": "Florida",
        "country": "Germany",
        "job_type": "Part-time",
        "title": "Analog Circuit Design manager"
    },
    {
        "job_id": 15,
        "job_desc": "ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus",
        "compnay_name": "Mastercard",
        "date": "2018-06-14",
        "city": "Greensboro",
        "state": "North Carolina",
        "country": "Germany",
        "job_type": "Full-time",
        "title": "Developer IV"
    },
    {
        "job_id": 16,
        "job_desc": "ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis",
        "compnay_name": "Mastercard",
        "date": "2018-08-08",
        "city": "Las Vegas",
        "state": "Nevada",
        "country": "Germany",
        "job_type": "Full-time",
        "title": "Pharmacist"
    },
    {
        "job_id": 17,
        "job_desc": "aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis",
        "compnay_name": "Mastercard",
        "date": "2018-08-09",
        "city": "Columbus",
        "state": "Ohio",
        "country": "Germany",
        "job_type": "Part-time",
        "title": "Design Engineer"
    },
    {
        "job_id": 18,
        "job_desc": "posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien",
        "compnay_name": "Mastercard",
        "date": "2018-01-04",
        "city": "Stamford",
        "state": "Connecticut",
        "country": "Canda",
        "job_type": "Part-time",
        "title": "Environmental Tech"
    },
    {
        "job_id": 19,
        "job_desc": "aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien",
        "compnay_name": "Mastercard",
        "date": "2018-01-15",
        "city": "Largo",
        "state": "Florida",
        "country": "Canda",
        "job_type": "Part-time",
        "title": "Physical Therapy Assistant"
    },
    {
        "job_id": 20,
        "job_desc": "pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in",
        "compnay_name": "Mastercard",
        "date": "2018-01-11",
        "city": "Myrtle Beach",
        "state": "South Carolina",
        "country": "Canda",
        "job_type": "Part-time",
        "title": "Engineer II"
    },
    {
        "job_id": 21,
        "job_desc": "amet lobortis sapien sapien non mi integer ac neque duis",
        "compnay_name": "Facebook",
        "date": "2018-09-21",
        "city": "Philadelphia",
        "state": "Pennsylvania",
        "country": "Canda",
        "job_type": "Part-time",
        "title": "Budget/Accounting Analyst III"
    },
    {
        "job_id": 22,
        "job_desc": "consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit",
        "compnay_name": "Bloomberg",
        "date": "2019-08-05",        
        "city": "Beaufort",
        "state": "South Carolina",
        "country": "Canda",
        "job_type": "Part-time",
        "title": "Dental Hygienist"
    },
    {
        "job_id": 23,
        "job_desc": "ac nulla sed vel enim sit amet nunc viverra dapibus nulla",
        "compnay_name": "Google",
        "date": "2019-08-23",
        "city": "Dallas",
        "state": "Texas",
        "country": "Canda",
        "job_type": "Full-time",
        "title": "Research Nurse"
    },
    {
        "job_id": 24,
        "job_desc": "lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas",
        "compnay_name": "Google",
        "date": "2018-02-10",
        "city": "Boston",
        "state": "Massachusetts",
        "country": "Canda",
        "job_type": "Full-time",
        "title": "Quality Engineer"
    },
    {
        "job_id": 25,
        "job_desc": "amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at",
        "compnay_name": "Bloomberg",
        "date": "2018-02-11",
        "city": "Norcross",
        "state": "Georgia",
        "country": "Canda",
        "job_type": "Full-time",
        "title": "Biostatistician III"
    },
    {
        "job_id": 26,
        "job_desc": "potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur",
        "compnay_name": "Bloomberg",
        "date": "2018-02-12",
        "city": "Garden Grove",
        "state": "California",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Accountant II"
    },
    {
        "job_id": 27,
        "job_desc": "sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed",
        "compnay_name": "Bloomberg",
        "date": "2018-02-13",
        "city": "Hampton",
        "state": "Virginia",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Accounting Assistant III"
    },
    {
        "job_id": 28,
        "job_desc": "posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet",
        "compnay_name": "Bloomberg",
        "date": "2018-02-14",
        "city": "Wilmington",
        "state": "Delaware",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Staff Accountant IV"
    },
    {
        "job_id": 29,
        "job_desc": "proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor",
        "compnay_name": "Bloomberg",
        "date": "2018-02-15",
        "city": "Sacramento",
        "state": "California",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Assistant Professor"
    },
    {
        "job_id": 30,
        "job_desc": "luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante",
        "compnay_name": "Bloomberg",
        "date": "2018-02-16",
        "city": "Fort Worth",
        "state": "Texas",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Quality Engineer"
    },
    {
        "job_id": 31,
        "job_desc": "primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus",
        "compnay_name": "Bloomberg",
        "date": "2018-02-17",
        "city": "Des Moines",
        "state": "Iowa",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Media Manager I"
    },
    {
        "job_id": 32,
        "job_desc": "diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat",
        "compnay_name": "Visa",
        "date": "2018-02-18",
        "city": "East Saint Louis",
        "state": "Illinois",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Recruiter"
    },
    {
        "job_id": 33,
        "job_desc": "at turpis a pede posuere nonummy integer non velit donec diam neque",
        "compnay_name": "Visa",
        "date": "2018-02-18",
        "city": "Arlington",
        "state": "Virginia",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Database Administrator II"
    },
    {
        "job_id": 34,
        "job_desc": "vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices",
        "compnay_name": "Visa",
        "date": "2018-02-19",
        "city": "Birmingham",
        "state": "Alabama",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Software Consultant"
    },
    {
        "job_id": 35,
        "job_desc": "hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
        "compnay_name": "Visa",
        "date": "2018-02-19",
        "city": "Seattle",
        "state": "Washington",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Information Systems Manager"
    },
    {
        "job_id": 36,
        "job_desc": "dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus",
        "compnay_name": "Visa",
        "date": "2018-02-20",
        "city": "El Paso",
        "state": "Texas",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Teacher"
    },
    {
        "job_id": 37,
        "job_desc": "non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales",
        "compnay_name": "Visa",
        "date": "2018-02-21",
        "city": "San Antonio",
        "state": "Texas",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Nurse"
    },
    {
        "job_id": 38,
        "job_desc": "cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut",
        "compnay_name": "Visa",
        "date": "2018-02-22",
        "city": "Fort Wayne",
        "state": "Indiana",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Paralegal"
    },
    {
        "job_id": 39,
        "job_desc": "rutrum neque aenean auctor gravida sem praesent id massa id nisl",
        "compnay_name": "Visa",
        "date": "2018-02-22",
        "city": "Miami Beach",
        "state": "Florida",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Chemical Engineer"
    },
    {
        "job_id": 40,
        "job_desc": "libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate",
        "compnay_name": "Visa",
        "date": "2018-02-24",
        "city": "Katy",
        "state": "Texas",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Quality Control Specialist"
    },
    {
        "job_id": 41,
        "job_desc": "eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum",
        "compnay_name": "Twitter",
        "date": "2018-02-23",
        "city": "Arlington",
        "state": "Texas",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Data Coordiator"
    },
    {
        "job_id": 42,
        "job_desc": "ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices",
        "compnay_name": "Rhybox",
        "date": "2018-02-23",
        "city": "Minneapolis",
        "state": "Minnesota",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Recruiter"
    },
    {
        "job_id": 43,
        "job_desc": "leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis",
        "compnay_name": "Fivespan",
        "date": "2018-02-25",
        "city": "Pompano Beach",
        "state": "Florida",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Staff Scientist"
    },
    {
        "job_id": 44,
        "job_desc": "eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa",
        "compnay_name": "Rhyzio",
        "date": "2018-02-25",
        "city": "Jacksonville",
        "state": "Florida",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Clinical Specialist"
    },
    {
        "job_id": 45,
        "job_desc": "in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum",
        "compnay_name": "Wordware",
        "date": "2018-02-26",
        "city": "Oklahoma City",
        "state": "Oklahoma",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Marketing Assistant"
    },
    {
        "job_id": 46,
        "job_desc": "eu mi nulla ac enim in tempor turpis nec euismod scelerisque",
        "compnay_name": "Zooveo",
        "date": "2018-02-07",
        "city": "Baton Rouge",
        "state": "Louisiana",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Financial Advisor"
    },
    {
        "job_id": 47,
        "job_desc": "condimentum id luctus nec molestie sed justo pellentesque viverra pede",
        "compnay_name": "Rhynyx",
        "date": "2018-02-19",
        "city": "Abilene",
        "state": "Texas",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Office Assistant III"
    },
    {
        "job_id": 48,
        "job_desc": "blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt",
        "compnay_name": "Shuffledrive",
        "date": "2018-02-12",
        "city": "El Paso",
        "state": "Texas",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Account Coordinator"
    },
    {
        "job_id": 49,
        "job_desc": "fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis",
        "compnay_name": "Leenti",
        "date": "2018-02-17",
        "city": "Florence",
        "state": "South Carolina",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Safety Technician II"
    },
    {
        "job_id": 50,
        "job_desc": "venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede",
        "compnay_name": "Tagchat",
        "date": "2018-02-17",
        "city": "Fresno",
        "state": "California",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Speech Pathologist"
    },
    {
        "job_id": 51,
        "job_desc": "odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt",
        "compnay_name": "Ooba",
        "date": "2018-02-20",
        "city": "Wichita Falls",
        "state": "Texas",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Project Manager"
    },
    {
        "job_id": 52,
        "job_desc": "in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut",
        "compnay_name": "Visa",
        "date": "2018-02-21",
        "city": "Mobile",
        "state": "Alabama",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Structural Analysis Engineer"
    },
    {
        "job_id": 53,
        "job_desc": "cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel",
        "compnay_name": "Mastercard",
        "date": "2018-02-21",
        "city": "El Paso",
        "state": "Texas",
        "country": "United States",
        "job_type": "Part-time",
        "title": "VP Marketing"
    },
    {
        "job_id": 54,
        "job_desc": "vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus",
        "compnay_name": "Katz",
        "date": "2018-02-11",
        "city": "Santa Rosa",
        "state": "California",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Human Resources Manager"
    },
    {
        "job_id": 55,
        "job_desc": "dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est",
        "compnay_name": "Yodoo",
        "date": "2018-03-01",
        "city": "Jackson",
        "state": "Mississippi",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Developer II"
    },
    {
        "job_id": 56,
        "job_desc": "amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor",
        "compnay_name": "Jayo",
        "date": "2018-03-11",
        "city": "Arlington",
        "state": "Virginia",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Automation Specialist I"
    },
    {
        "job_id": 57,
        "job_desc": "hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id",
        "compnay_name": "Latz",
        "date": "2018-03-02",
        "city": "Austin",
        "state": "Texas",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Research Nurse"
    },
    {
        "job_id": 58,
        "job_desc": "sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam",
        "compnay_name": "Dablist",
        "date": "2018-03-09",
        "city": "Danbury",
        "state": "Connecticut",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Executive Secretary"
    },
    {
        "job_id": 59,
        "job_desc": "vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat",
        "compnay_name": "Twinte",
        "date": "2018-03-06",
        "city": "Inglewood",
        "state": "California",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Executive Secretary"
    },
    {
        "job_id": 60,
        "job_desc": "id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam",
        "compnay_name": "DabZ",
        "date": "2018-04-05",
        "city": "Wichita Falls",
        "state": "Texas",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Operator"
    },
    {
        "job_id": 61,
        "job_desc": "nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio",
        "compnay_name": "Wikizz",
        "date": "2018-04-04",
        "city": "Winston Salem",
        "state": "North Carolina",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Database Administrator III"
    },
    {
        "job_id": 62,
        "job_desc": "luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida",
        "compnay_name": "Twitter",
        "date": "2018-06-06",
        "city": "Bakersfield",
        "state": "California",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Structural Engineer"
    },
    {
        "job_id": 63,
        "job_desc": "magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor",
        "compnay_name": "Google",
        "date": "2018-05-05",
        "city": "Rochester",
        "state": "New York",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Biostatistician I"
    },
    {
        "job_id": 64,
        "job_desc": "amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce",
        "compnay_name": "Blogspan",
        "date": "2018-07-07",
        "city": "Spartanburg",
        "state": "South Carolina",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Social Worker"
    },
    {
        "job_id": 65,
        "job_desc": "scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus",
        "compnay_name": "Meetz",
        "date": "2018-08-08",
        "city": "New York City",
        "state": "New York",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Accounting Assistant II"
    },
    {
        "job_id": 66,
        "job_desc": "sed augue aliquam erat volutpat in congue etiam justo etiam",
        "compnay_name": "Youtags",
        "date": "2018-06-08",
        "city": "Kansas City",
        "state": "Kansas",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Programmer I"
    },
    {
        "job_id": 67,
        "job_desc": "justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit",
        "compnay_name": "Babbleset",
        "date": "2018-09-09",
        "city": "Battle Creek",
        "state": "Michigan",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Software Consultant"
    },
    {
        "job_id": 68,
        "job_desc": "ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis",
        "compnay_name": "Twitter",
        "date": "2018-10-01",
        "city": "New Orleans",
        "state": "Louisiana",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Internal Auditor"
    },
    {
        "job_id": 69,
        "job_desc": "nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede Part-timesuada in imperdiet et",
        "compnay_name": "Twitter",
        "date": "2018-10-11",
        "city": "Dallas",
        "state": "Texas",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Help Desk Operator"
    },
    {
        "job_id": 70,
        "job_desc": "at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam",
        "compnay_name": "Twitter",
        "date": "2018-10-12",
        "city": "Corpus Christi",
        "state": "Texas",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Web Developer II"
    },
    {
        "job_id": 71,
        "job_desc": "odio cras mi pede Part-timesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet",
        "compnay_name": "Twitter",
        "date": "2018-11-12",
        "city": "Norwalk",
        "state": "Connecticut",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Tax Accountant"
    },
    {
        "job_id": 72,
        "job_desc": "magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis",
        "compnay_name": "Twitter",
        "date": "2018-12-22",
        "city": "Wilkes Barre",
        "state": "Pennsylvania",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Physical Therapy Assistant"
    },
    {
        "job_id": 73,
        "job_desc": "faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras",
        "compnay_name": "Youbridge",
        "date": "2018-12-12",
        "city": "Greeley",
        "state": "Colorado",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Desktop Support Technician"
    },
    {
        "job_id": 74,
        "job_desc": "tristique est et tempus semper est quam pharetra magna ac consequat metus sapien",
        "compnay_name": "Twitter",
        "date": "2018-12-16",
        "city": "Brooklyn",
        "state": "New York",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Junior Executive"
    },
    {
        "job_id": 75,
        "job_desc": "eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi",
        "compnay_name": "Google",
        "date": "2018-12-19",
        "city": "Hayward",
        "state": "California",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Project Manager"
    },
    {
        "job_id": 76,
        "job_desc": "purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor",
        "compnay_name": "Twitter",
        "date": "2018-11-25",
        "city": "Fort Worth",
        "state": "Texas",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Chemical Engineer"
    },
    {
        "job_id": 77,
        "job_desc": "diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis",
        "compnay_name": "Twitter",
        "date": "2018-11-22",
        "city": "Flint",
        "state": "Michigan",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Senior Financial Analyst"
    },
    {
        "job_id": 78,
        "job_desc": "erat id mauris vulputate elementum nullam varius nulla facilisi cras",
        "compnay_name": "Twitter",
        "date": "2018-11-20",
        "city": "Dallas",
        "state": "Texas",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Software Test Engineer IV"
    },
    {
        "job_id": 79,
        "job_desc": "ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur",
        "compnay_name": "Jaxspan",
        "date": "2018-11-19",
        "city": "Fullerton",
        "state": "California",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Biostatistician IV"
    },
    {
        "job_id": 80,
        "job_desc": "quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat",
        "compnay_name": "Twitterlist",
        "date": "2018-10-11",
        "city": "Trenton",
        "state": "New Jersey",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Structural Analysis Engineer"
    },
    {
        "job_id": 81,
        "job_desc": "aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus",
        "compnay_name": "Vipe",
        "date": "2018-11-19",
        "city": "Lexington",
        "state": "Kentucky",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Systems Administrator III"
    },
    {
        "job_id": 82,
        "job_desc": "justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum",
        "compnay_name": "Skilith",
        "date": "2018-10-27",
        "city": "Miami",
        "state": "Florida",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Senior Cost Accountant"
    },
    {
        "job_id": 83,
        "job_desc": "non sodales sed tincidunt eu felis fusce posuere felis sed",
        "compnay_name": "Quatz",
        "date": "2018-10-13",
        "city": "Irving",
        "state": "Texas",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Analog Circuit Design manager"
    },
    {
        "job_id": 84,
        "job_desc": "eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi",
        "compnay_name": "Bubbletube",
        "date": "2018-10-12",
        "city": "Portland",
        "state": "Oregon",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Biostatistician IV"
    },
    {
        "job_id": 85,
        "job_desc": "sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce",
        "compnay_name": "Visa",
        "date": "2018-10-04",
        "city": "El Paso",
        "state": "Texas",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Structural Engineer"
    },
    {
        "job_id": 86,
        "job_desc": "leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in",
        "compnay_name": "Aivee",
        "date": "2018-10-02",
        "city": "El Paso",
        "state": "Texas",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Automation Specialist I"
    },
    {
        "job_id": 87,
        "job_desc": "molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus",
        "compnay_name": "Bloomberg",
        "date": "2018-12-22",
        "city": "Houston",
        "state": "Texas",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Mechanical Systems Engineer"
    },
    {
        "job_id": 88,
        "job_desc": "a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in",
        "compnay_name": "Snaptags",
        "date": "2018-02-06",
        "city": "Van Nuys",
        "state": "California",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Clinical Specialist"
    },
    {
        "job_id": 89,
        "job_desc": "et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient",
        "compnay_name": "Meedoo",
        "date": "2019-02-04",
        "city": "Boston",
        "state": "Massachusetts",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Librarian"
    },
    {
        "job_id": 90,
        "job_desc": "a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet",
        "compnay_name": "Oodoo",
        "date": "2019-02-10",
        "city": "Chula Vista",
        "state": "California",
        "country": "United States",
        "job_type": "Part-time",
        "title": "VP Quality Control"
    },
    {
        "job_id": 91,
        "job_desc": "sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet",
        "compnay_name": "Plambee",
        "date": "2019-02-19",
        "city": "Newport News",
        "state": "Virginia",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Operator"
    },
    {
        "job_id": 92,
        "job_desc": "turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam",
        "compnay_name": "Eabox",
        "date": "2019-06-01",
        "city": "Mesa",
        "state": "Arizona",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Nurse"
    },
    {
        "job_id": 93,
        "job_desc": "quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus",
        "compnay_name": "Jabberbean",
        "date": "2019-08-01",
        "city": "San Diego",
        "state": "California",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Software Engineer II"
    },
    {
        "job_id": 94,
        "job_desc": "felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis",
        "compnay_name": "Centimia",
        "date": "2019-04-01",
        "city": "Evansville",
        "state": "Indiana",
        "country": "United States",
        "job_type": "Part-time",
        "title": "Quality Engineer"
    },
    {
        "job_id": 95,
        "job_desc": "ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu",
        "compnay_name": "Miboo",
        "date": "2019-03-01",
        "city": "Baltimore",
        "state": "Maryland",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Actuary"
    },
    {
        "job_id": 96,
        "job_desc": "etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit",
        "compnay_name": "Zoomzone",
        "date": "2019-07-01",
        "city": "Philadelphia",
        "state": "Pennsylvania",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Speech Pathologist"
    },
    {
        "job_id": 97,
        "job_desc": "curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec",
        "compnay_name": "Linktype",
        "date": "2019-09-01",
        "city": "Paterson",
        "state": "New Jersey",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Librarian"
    },
    {
        "job_id": 98,
        "job_desc": "augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum",
        "compnay_name": "Visa",
        "date": "2019-12-01",
        "city": "Oakland",
        "state": "California",
        "country": "United States",
        "job_type": "Full-time",
        "title": "Automation Specialist IV"
    }
]

export {job_data};